# Generated by Django 5.0.3 on 2024-03-22 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pages.users')),
                ('officeNo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pages.users')),
                ('phoneNumber', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pages.users')),
                ('phoneNumber', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'EventOrganizer',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('eventDateTime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('artist', models.CharField(blank=True, max_length=100, null=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('imageURL', models.CharField(blank=True, max_length=100, null=True)),
                ('adminID', models.ForeignKey(blank=True, db_column='adminID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.admin')),
                ('eventOrganizerID', models.ForeignKey(blank=True, db_column='eventOrganizerID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.eventorganizer')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='BookedEvent',
            fields=[
                ('eventID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pages.events')),
                ('quantity', models.IntegerField()),
                ('isPaid', models.BooleanField()),
                ('referenceNumber', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.users')),
            ],
            options={
                'db_table': 'bookedEvent',
            },
        ),
    ]
