version: '3.8'

services:
  web:
    container_name: communicado_container_test
    build:
      context: ./
      dockerfile: ./Dockerfile.test
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./communicado_eticketing/:/usr/src/communicado_eticketing/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
