name: Django Coverage Test

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        cd ./Django/communicado
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        python manage.py makemigrations
        python manage.py migrate || true
        coverage run manage.py test
        coverage report
        coverage html -d coverage_report

    - name: Delete test database
      run: |
        cd ./Django/communicado
        python manage.py flush --no-input        

    - name: Save coverage report artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage_report
