name: Pull on Push

on:
  workflow_run:
    workflows: ["Running Tests"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
    
jobs:
  pull:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: SSH and Pull Changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ./pull_changes.sh

      - name: Print End Status
        run: |
          echo "Code Pushed to Production"
