name: Running Tests

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    retry:
      max-runs: 3    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Docker Build Image
      run: |
        cd ./Django/communicado
        chmod +x mac_testing.sh
        ./mac_testing.sh

    - name: Run Django migrations
      run: |
        cd ./Django/communicado
        docker exec communicado_container_test python manage.py makemigrations
        docker exec communicado_container_test python manage.py migrate || true

    - name: Run Tests
      run: |
        cd ./Django/communicado
        docker exec communicado_container_test python manage.py test

    - name: Print End Status
      run: |
        echo "Tests completed."
