name: Running Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          cd ./Django/communicado
          chmod +x mac_docker_build_and_run.sh
          ./mac_docker_build_and_run.sh

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          cd ./Django/communicado
          docker-compose run web python manage.py test
