name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd Django/communicado
        docker-compose build
    - name: Test selenium
      run: |
        cd Django/communicado
        docker-compose run web python manage.py test
    
